#ddev-generated
services:
  typo3-solr:
    container_name: ddev-${DDEV_SITENAME}-typo3-solr
    hostname: ${DDEV_SITENAME}-typo3-solr
    image: solr:9.4
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTPS_EXPOSE=8983
      - HTTP_EXPOSE=8983
    volumes:
      - ./typo3-solr/data:/var/solr/data
  web:
    links:
      - typo3-solr
